[api]
address = "127.0.0.1:8080"
rest_api = "127.0.0.1:8000"

[model]
data_type = "F32"
precision = 53

[process]
rounds = 25
participants = 10
strategy = "FedAvg"

[s3]
access_key = "modalic"
secret_access_key = "12345678"
region = ["minio", "http://localhost:9000"]
bucket = "mnist-cnn-testing"
global_model = "cnn_global"
