[api]
address = "127.0.0.1:8080"
rest_api = "127.0.0.1:5000"

[model]
data_type = "F32"
length = 4

[process]
rounds = 5
participants = 3
strategy = "FedAvg"

[log]
filter = "mosaic=debug,info"

[s3]
access_key = "modalic"
secret_access_key = "12345678"
region = ["minio", "http://localhost:9000"]
bucket = "mnist-cnn-testing"
global_model = "cnn_global"

