[api]
address = "127.0.0.1:8080"
rest_api = "127.0.0.1:8010"

[model]
data_type = "F32"
length = 4

[job]
job_id = 1
job_token = "test"
route = "http://localhost:5000/api/communication_rounds/create_communication_round"

[process]
rounds = 25
participants = 10
strategy = "FedAvg"

[log]
filter = "mosaic=debug,info"

[s3]
access_key = "modalic"
secret_access_key = "12345678"
region = ["minio", "http://localhost:9000"]
bucket = "mnist-cnn-testing"
global_model = "cnn_global"
