[api]
server_address = "127.0.0.1:8080"
rest_api = "127.0.0.1:8000"

[model]
data_type = "F32"
precision = 53

[job]
job_id = 0
job_token = "0"
route = "http://localhost:5000/api/communication_rounds/create_communication_round"

[process]
training_rounds = 0
participants = 0
strategy = "FedAvg"

[log]
filter = "mosaic=debug,info"

[s3]
access_key = "modalic"
secret_access_key = "modalic"
region = ["minio", "http://localhost:9000"]
bucket = "modalic-testing"
global_model = "global_model"
